spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sosial_damoa?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8
    username: damoa
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: kimkongpp1223@gmail.com
    password: ceotogcykrgyxuzu  #구글계정 앱 생성 키
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

file:
  upload-dir: C:/uploads